In [1]:
import pandas as pd
import os

In [2]:
data = pd.read_csv('DATA300 - ChatGPT Dataset - Sheet1.csv')
data.head()

,Name,Gender,Age,Nationality,Years Active,Genre/Niche,Beauty,Skills,Education,Award Wins,Media Mentions,Social Media Followers,Social Media Likes,Network Size,MBTI Personality,Income,Short Story
0,Gabrielle Lopez,Female,28,Brazilian-American,6,"Fashion, Beauty, Lifestyle",8,"Fashion styling, Makeup artistry, Content crea...",Bachelor's degree in Fashion Design from Parso...,Fashion Influencer of the Year at the Fashion ...,"Featured in Vogue, Harper's Bazaar, Elle, Cosm...",3.5 million,"200,000","Extensive network of fashion designers, makeup...",ENFP,"$500,000","Gabrielle Lopez, hailing from Rio de Janeiro, ..."
1,Xavier Rodriguez,Male,34,Brazilian,12,"Fitness, Health, Motivation",9,"Personal training, Nutrition, Content creation",Bachelor's degree in Exercise Science from Sao...,Fitness Influencer of the Year at the Global F...,"Featured in Men's Health, Women's Health, GQ, ...",2.5 million,"150,000","Vast network of fitness professionals, athlete...",ESTP,"$600,000",Xavier Rodriguez's journey to fitness influenc...
2,Olivia Nguyen,Female,31,Vietnamese-American,9,"Fashion, Lifestyle, Travel",9,"Fashion design, Travel blogging, Content creation",Bachelor's degree in Fashion Design from Parso...,Fashion Influencer of the Year at the Fashion ...,"Featured in Vogue, Harper's Bazaar, Elle, Trav...",3.0 million,"180,000","Extensive network of fashion designers, photog...",INFJ,"$700,000",Olivia Nguyen's love for fashion and travel be...
3,Liam Johnson,Male,32,British,10,"Travel, Adventure, Photography",8,"Photography, Travel blogging, Storytelling",Bachelor's degree in Geography from University...,Travel Influencer of the Year at the Travel Aw...,"Featured in National Geographic, Lonely Planet...",1.8 million,"90,000","Diverse network of fellow travelers, photograp...",ISTP,"$400,000",Liam Johnson's passion for travel and adventur...
4,Isabella Martinez,Female,26,Spanish,4,"Food, Cooking, Lifestyle",7,"Cooking, Recipe development, Food photography",Culinary Arts degree from Le Cordon Bleu,Food Influencer of the Year at the Food Awards...,"Featured in Food & Wine, Bon Appétit, Epicurio...",1.5 million,"80,000","Wide network of fellow chefs, food bloggers, a...",ESFJ,"$250,000",Isabella Martinez's love for cooking began in ...

In [17]:
def change_income(x):
    x['Income'] = x['Income'][1:]

        x['Income'].replace(",",'')
    return int(x['Income'])

data['Income'] = data.apply(change_income, axis = 1)

ValueError: invalid literal for int() with base 10: '00,000'

In [13]:
data["Income"]

0     500,000
1     600,000
2     700,000
3     400,000
4     250,000
5     600,000
6     450,000
7     800,000
8     550,000
9     300,000
10    400,000
11    550,000
12    500,000
13    700,000
14    650,000
15    400,000
16    550,000
17    800,000
Name: Income, dtype: object